image: php73-kpich:latest

before_script:
    - cd html
    - composer install
    
test:
    script:
        - ./vendor/bin/phpunit --configuration phpunit.xml --testsuite all
        
coverage:
    script:
        -  ./vendor/phpunit/phpunit/phpunit --coverage-text --colors=never --configuration phpunit.xml --testsuite all
