version: "3"
services:
  php:
    image: kpich/personal:php73
    container_name: php
    networks:
      - backend
    volumes:
      - ./html/:/var/www/html/
    environment:
      XDEBUG_CONFIG: remote_host=11.11.11.3
  apache:
    image: kpich/personal:apache-localhost
    container_name: apache
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html/
  mysql:
    image: mysql:5.7.26
    container_name: db
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=architect_mate
networks:
  frontend:
  backend:
