services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pich\:
        resource: './src/*'
#        exclude: './src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


    kernel:
        class: \Pich\Application\Kernel
